# Generated by Django 3.2.13 on 2022-04-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0002_auto_20220425_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canton',
            old_name='gid',
            new_name='id',
        ),
    ]
